# Generated by Django 4.2 on 2023-04-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
