# Generated by Django 4.2 on 2023-04-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_session_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=4)),
                ('peak_rank', models.CharField(default='Iron 1', max_length=20)),
                ('rank', models.CharField(default='Iron 1', max_length=20)),
                ('matches_played', models.IntegerField(default=0, max_length=3)),
                ('matches_won', models.IntegerField(default=0, max_length=3)),
                ('k_d', models.CharField(default='0.0', max_length=5)),
                ('hs_percent', models.CharField(default='0.0', max_length=5)),
                ('damage_per_round', models.CharField(default='0.0', max_length=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
