# Generated by Django 4.2 on 2023-04-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_valorantdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorantdata',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valorantdata',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
