# Generated by Django 4.2 on 2023-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
