# Generated by Django 4.2 on 2023-04-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_session_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_insta',
            new_name='social_instagram',
        ),
    ]
