# Generated by Django 4.2 on 2023-04-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_social_insta_profile_social_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.coachprofile'),
        ),
    ]
