# Generated by Django 4.2 on 2023-04-07 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_review_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='coachID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.coachprofile'),
        ),
    ]
