# Generated by Django 4.2 on 2023-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_booksession_bookuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksession',
            name='session_price',
            field=models.IntegerField(choices=[(500, '500 Tk'), (1000, '1000 Tk'), (2000, '2000 Tk')]),
        ),
    ]
