# Generated by Django 4.2 on 2023-04-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_booksession_session_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True),
        ),
    ]
