# Generated by Django 4.2 on 2023-04-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], default='up', max_length=200, null=True),
        ),
    ]
