# Generated by Django 4.2 on 2023-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_newsportalpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsportalpost',
            name='post_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
