# Generated by Django 4.2 on 2023-04-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_tag_alter_newsportalpost_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksession',
            name='session_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booksession',
            name='session_time',
            field=models.TimeField(null=True),
        ),
    ]
